### ISSUE TITLE
Get base64 encoded string instead of file picker

### ISSUE THREAD

**Issue by MaximilianLloyd** [romgrk/kirby.nvim#1]
![image](https://user-images.githubusercontent.com/10583205/219042783-65f50697-93b7-4ffe-a76f-80f4b06e2a99.png)

Hi, this is what shows up when trying to use the file picker. I'm using kitty, but with Tmux. is it Tmux that is the issue?

**Comment by romgrk** [comment]
Yes, very probable. Did you test without tmux?

I woud recommend to use kitty's own layout system instead of tmux: https://sw.kovidgoyal.net/kitty/layouts/#arrange-windows

**Comment by mosheavni** [comment]
same happens to me, i'm using iTerm2, no tmux.

**Comment by romgrk** [comment]
You need to use the kitty terminal. See the docs for the requirements: https://github.com/romgrk/kirby.nvim#installation
