### ISSUE TITLE
Bug: window doesn't open

### ISSUE THREAD

**Issue by williamhCode** [romgrk/kirby.nvim#2]
I just installed the plugin, and I get this error when doing <C-p>
<img width="1469" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/83525937/90007c75-7cda-495d-afd7-dc6a10b26a2c">

Edit:  
macOS 12.6, NVIM v0.10.0-dev-415+g55f6a1cab-Homebrew

`vim.print(config)` on line 20204 gives:
```
{
  col = nan,
  height = nan,
  noautocmd = true,
  relative = "editor",
  row = nan,
  style = "minimal",
  width = nan
}
```

**Comment by romgrk** [comment]
Can you share some details about your environment? OS, versions.

If you're able to add a print statement at the indicated line it would also help be a lot, thanks.

**Comment by jannemecek** [comment]
I'm on macOS 13.4, Kitty 0.28.1, nvim 0.9.0 (the release version) if that's of any use. I'm also using Packer instead of lazy, but I'm gettin the same error as @williamhCode 

This is the line btw
<img width="848" alt="Screenshot 2023-06-08 at 13 26 59" src="https://github.com/romgrk/kirby.nvim/assets/12463178/4dcd728e-6b4b-4e53-bbf0-2a34609c145e">

Printing config pairs gets me
```relative editor                                                                                                                                                                        
style minimal                                                                                                                                                                          
noautocmd true                                                                                                                                                                         
width nan                                                                                                                                                                              
col nan                                                                                                                                                                                
row nan                                                                                                                                                                                
height nan

**Comment by avegancafe** [comment]
+1, also happening for me as well. Happy to share whatever other info you need

**Comment by romgrk** [comment]
Can't reproduce the issue :/ Ima be honest, if someone could debug the stacktrace there and find where that `nan` is coming from, it's the only way I could provide support here.

**Comment by avegancafe** [comment]
Sure I’ll give it a shot! This would be so cool if it worked

**Comment by romgrk** [comment]
Oooh maybe it's the font size. So kui.nvim tries to get the font size from the kitty.conf, and also from `set guifont`. If none of them is there, it might be causing the `nan`. Can you try setting the font family & size manually? Something like this:

```viml
let &guifont='JetBrainsMono Nerd Font:h20'
```

**Comment by avegancafe** [comment]
Ohh interesting yeah I'll give that a try as well. FWIW, if you want to look through my config to see if there's anything that stands out it's here: https://github.com/avegancafe/juliet . Under the folder `kitty` and `nvim` at the top level

**Comment by avegancafe** [comment]
Took me a minute to grab these @romgrk sorry about that, but here's what I found:

<img width="748" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/2652762/1ecb105b-6135-4306-8e2d-cea8f2e95645">

<img width="1552" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/2652762/98b3d97b-367a-4b08-8a27-98723b3a9ee2">

Seems like the NaN comes from the `settings.DIMENSIONS.cell_pixels.width` being `0`, although all of those constituent values are also zero...

**Comment by romgrk** [comment]
Can you pull the latest master and try again?

If it still fails, can you:
 - run `:lua require('kui.legacy.state').update_dimensions()`
 - run `:lua vim.print(require('kui.legacy.state').dimensions`
 - run `:lua vim.print(require('kui').settings.DIMENSIONS`

The dimensions update logic is here, maybe the syscall is wrong for macOS:

https://github.com/romgrk/kui.nvim/blob/02295598535d3a6f867be00a9edc4d91fe7862ac/lua/kui/legacy/state.lua#L34-L53

**Comment by avegancafe** [comment]
After running that `update_dimensions` method, here's the output from running `:lua vim.print(require('kui.legacy.state').dimensions)`:

<img width="1552" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/2652762/38864bd8-6cac-418e-976f-4ad9de1bbbff">

Output from running `:lua vim.print(require('kui').settings.DIMENSIONS)`:

<img width="1552" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/2652762/a0b3162d-6954-407e-9e58-08a4d9698ce6">

**Comment by romgrk** [comment]
Try again with latest master? I've adjusted the `ioctl` syscall but I don't have a macOS system to test it with.

**Comment by avegancafe** [comment]
That worked! Nice!

<img width="1552" alt="image" src="https://github.com/romgrk/kirby.nvim/assets/2652762/b4f02ac2-093d-43f9-9322-35adacf95181">

**Comment by romgrk** [comment]
Great! You probably want to adjust the font family & size with `guifont`, and it's meant to be used with a https://www.nerdfonts.com/. You can open a new issue if you find any more bugs.
